### PR TITLE
ci: Update pylint ignores

### PR DESCRIPTION
**Pull request by jamesholland-uk**
## Description
Update ignores files for sanity checking to include pylint checks for `used-before-assignment`

## Motivation and Context
This check has been providing inconsistent results, and flags in the Red Hat ingestion pipeline.
In [6.20.1](https://github.com/ansible/ansible-lint/releases/tag/v6.20.1), `pylint:used-before-assignment` [was added to the allowed ignores list](https://github.com/ansible/ansible-lint/pull/3766/files#diff-7519dc3bafc1e0f507d50963174ebdeb205e56bf68f27eb4dc980658bbe79e6c). This means we can add it to our ignores list to get a clean import through the ingestion pipeline.

## How Has This Been Tested?
Tested locally

## Types of changes
- Bug fix (non-breaking change which fixes an issue)

## Checklist
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jamesholland-uk** [comment]
@alisonlhart Does this look like the correct way to add the ignore for `used-before-assignment`? Thanks :-)

**Comment by jamesholland-uk** [comment]
Currently seeing this is unnecessary:
```
ERROR: Found 2 pylint issue(s) which need to be resolved:
ERROR: tests/sanity/ignore-2.14.txt:109:1: ansible-test: Ignoring 'used-before-assignment' on 'plugins/modules/panos_object_facts.py' is unnecessary
ERROR: tests/sanity/ignore-2.14.txt:110:1: ansible-test: Ignoring 'used-before-assignment' on 'plugins/modules/panos_query_rules.py' is unnecessary
```

**Comment by alisonlhart** [comment]
@jamesholland-uk It appears the trigger for those errors is no longer present in the code in the most recent release, 2.17.7. In the previous release 2.17.6, they were still present, but not anymore. We haven't changed the version of ansible-core we're using in the pipeline (2.15.0), so it can't be a change on the ansible side. That's interesting. I'll have to take a closer look to see why that's the case, but as for now it looks like those ignores aren't required to pass pylint anymore. If that error appears again in a future code change, feel free to re add them!

**Comment by jamesholland-uk** [comment]
Thanks @alisonlhart, I'll close this then, we can re-add if needed later down the line.

**Pull request closed without merging**
