### PR TITLE
feat: Add `panos_nat_rule2`

### PR DESCRIPTION
**Pull request by shinmog**

### CODE REVIEW

**Comment by fhsctv** [comment]
Is there any migration guide on how to migrate from panos_nat_rule to panos_nat_rule2?

**Comment by fhsctv** [comment]
@jamesholland-uk thank you for your effort!

It is almost perfect. I don't know if that was intended in panos_nat_rule2 but the module default for the "to_interface" parameter changed from "any" to null/not set

When I run the migrated playbook against my test system, the configuration changes for some nat rules, where the parameter "to_interface" is not set.

I think, this should also be documented in the migration guide.

**Comment by jamesholland-uk** [comment]
Thanks for the review and suggestion @fhsctv. I've added three changes in default values to the migration article, let me know what you think

**Comment by fhsctv** [comment]
@jamesholland-uk : Thank you! That's helps a lot now!

**Comment by jamesholland-uk** [comment]
Brilliant. It is live now: https://pan.dev/ansible/docs/panos/info/nat_rule_v3

**Pull request merged**
