### PR TITLE
Virtual router idempotent fix - Issue #191

### PR DESCRIPTION
**Pull request by dstogsdill**
## Description

Updated the ```panos_virtual_router.py``` module to fix idempotency.  

**EDIT:** I am removing the interface changes from this pull so that it does not change current behavior.  This pull only include a fix when there are more than one child objects.

1. Module will no longer detect a change when a child object (BGP, OSPF, Static route, etc) is configured.
<s>2. Module will no longer detect a change when an interface is added to the virtual router outside of this module</s>

## Motivation and Context

See [Issue #191 for details](https://github.com/PaloAltoNetworks/pan-os-ansible/issues/191)

## How Has This Been Tested?

I'm currently testing against a Lab Panorama VE instance.  I'm also testing locally using a venv python 3.7 & ansible 2.10.  

I've run the following test scenarios which have passed.

1. Create net new Virtual Router with all arguments populated
2. Change argument to VR in playbook - Pass
<s>3. Add a new interface to VR in playbook - Pass
4. Manually add interface to VR, run playbook to validate no change detected - Pass
       - Manually add new interface to VR, Add new interface to playbook, run playbook and verify:
       - Manually added interface is NOT removed - Pass
7. Ansible added interface is added - Pass</s>
8. Manually add OSPF & BGP policy, run play book to verify no change is detected - Pass

## Screenshots (if appropriate)

Screen Shot 2021-02-13 at 1 30 34 PM

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

I am currently running the integration tests and will upload my results shortly

- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [X ] All new and existing tests passed.

### CODE REVIEW

**Comment by dstogsdill** [comment]
Not sure why this failed.  Any insight would be appreciated!

**Comment by dstogsdill** [comment]
Adding my integration test results
[integration_result.txt](https://github.com/PaloAltoNetworks/pan-os-ansible/files/6200303/integration_result.txt)

**Comment by mrichardson03** [comment]
Thank you for your contribution!

Please extend the integration tests to account for this scenario, and add the output to this PR.  Running only the single test `test_panos_virtual_router` is sufficient.

**Review by mrichardson03 — CHANGES_REQUESTED** [review]
Thank you for your contribution!

Please extend the integration tests to account for this scenario, and add the output to this PR. Running only the single test test_panos_virtual_router is sufficient.

**Comment by shinmog** [comment]
Closing this out; the collection's code has significantly changed since this PR was opened.

**Pull request closed without merging**
