### PR TITLE
Added wait_for argument to provide more flexibility in panos_check.py

### PR DESCRIPTION
**Pull request by patrickdaj**
## Description
This PR adds a new argument to panos_check.py that should make it more useful without breaking existing functionality. 

## Motivation and Context

Many platforms such as the PA-5200 series will not work all that well with the existing module for things like reboots due to the fact that autocommit sometimes takes some time to even start.  This can lead to failures of this module before the autocommit has completed.

Additionally, a method of waiting for HA to be up is also useful as a check point of how up a system really is.  The autocommit option should be a better indication of a rebooted system being ready than the prior check of all jobs.

## How Has This Been Tested?

The original function was left alone that checked for all jobs.  It was also left as the default so as not to break existing ansible code.  It was tested against a variety of platforms as a replacement.

## Screenshots (if appropriate)
```
  hosts: vm100
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: panos_check autocommit
      panos_check:
        provider: "{{ provider }}"
        wait_for: autocommit

    - name: panos_check ha
      panos_check:
        provider: "{{ provider }}"
        wait_for: ha

    - name: panos_check standard - implicit
      panos_check:
        provider: "{{ provider }}"

    - name: panos_check standard - explicit
      panos_check:
        provider: "{{ provider }}"
        wait_for: jobs
```

```
(venv) patrick@buntu:~/PycharmProjects/ansible-testing$ ansible-playbook -i hosts.yaml test.yaml

PLAY [panos test playbook] ******************************************************************************************************************************************

TASK [panos_check autocommit] ***************************************************************************************************************************************
changed: [vm100]

TASK [panos_check ha] ***********************************************************************************************************************************************
changed: [vm100]

TASK [panos_check standard - implicit] ******************************************************************************************************************************
changed: [vm100]

TASK [panos_check standard - explicit] ******************************************************************************************************************************
changed: [vm100]

PLAY RECAP **********************************************************************************************************************************************************
vm100                      : ok=4    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 

```
## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have updated the documentation accordingly.
- [X ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

I don't see any test framework for the new collection.  I'd be glad to contribute a test for this if that was somewhere in the repo.

### CODE REVIEW

**Comment by mrichardson03** [comment]
Thanks for the contribution, but checking `show chassis-ready` covers all these cases.  #34 should simplify these checks.

**Comment by patrickdaj** [comment]
> Thanks for the contribution, but checking `show chassis-ready` covers all these cases. #34 should simplify these checks.

Actually not true.  For all platforms other that PA-7080 yes you are correct.  PA-7080 and probably other chassis based PAs don't support that command.  That was the reason I approached it by checking for autocommit rather than running that command.

And also show chassis-ready does not validate that HA is up either.  If you don't see the value oh well.  Just pointing out that what you said is actually not correct.

**Comment by mrichardson03** [comment]
I'll have to do more research around the PA-7000s.  I'm trying to find a better solution than relying on the autocommit job, because that job will disappear once the firewall has been running for a while.

**Comment by patrickdaj** [comment]
> I'll have to do more research around the PA-7000s. I'm trying to find a better solution than relying on the autocommit job, because that job will disappear once the firewall has been running for a while.

Did you ever come up with a solution for this?

**Comment by mrichardson03** [comment]
> Did you ever come up with a solution for this?

Only a super hacky one: look for the autocommit job succeeding, but if you don't find one, look at the firewall's uptime and if it's been long enough, return True.

**Pull request closed without merging**
